import '../styles/globals.css'
import '../styles/fonts.css'
import Header from './components/header' 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{fontFamily: "Nunito Sans", backgroundColor: "hsl(0, 0%, 98%)"}} className="h-screen m-0">
        <Header/>
        <div 
        style={{
          backgroundColor: "hsl(0, 0%, 98%)",
          borderColor: "hsl(0, 0%, 92%)",
        }} 
        className="border-t-4 border-solid">
          {children}
        </div>
      </body>
    </html>
  )
}
