import '../styles/globals.css'
import '../styles/fonts.css'
import Header from './components/header' 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{fontFamily: "Nunito Sans", backgroundColor: "hsl(0, 0%, 98%)"}} className="min-h-screen m-0 overflow-y-auto">
        <Header/>
        <div 
          style={{
            backgroundColor: "hsl(0, 0%, 98%)",
            borderColor: "hsl(0, 0%, 92%)",
          }} 
          className="relative border-t-4 border-solid">
            {children}
        </div>
      </body>
    </html>
  )
}
