import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faMoon
} from "@fortawesome/free-solid-svg-icons";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        margin: "0",
        height: "100dvh"
      }}>
        <div style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "20px",
          backgroundColor: "white"
        }}>
          <h1>Where in the world?</h1>
          <div style={{
            display: "flex",
            alignItems: "center",
            gap: "10px",
          }}>
            <FontAwesomeIcon icon={faMoon} size="2xs"/>
            <span>Dark Mode</span>
          </div>
        </div>
        <div style={{
          backgroundColor: "hsl(0, 0%, 98%)",
          borderTopWidth: "3px",
          borderTopStyle: "solid",
          borderColor: "hsl(0, 0%, 92%)",
          padding: "20px",
        }}>
          {children}
        </div>
      </body>
    </html>
  )
}
